service_name: "test-middleware"
environment: "development"
log_level: "DEBUG"
mock_mode: true  # Run without Lattice connection

# Single test drone
drones:
  - id: "test-drone-1"
    connection_string: "udp://:14540"
    type: "quadcopter"
    manufacturer: "Generic"
    model: "SITL"
    capabilities: ["mapping", "relay", "dropping"]
    max_altitude: 120.0
    max_speed: 20.0
    max_flight_time: 1800  # 30 minutes
    geofence_enabled: true
    rtl_altitude: 50.0
    failsafe_action: "RTL" 